# Generated by Django 5.1.3 on 2024-11-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='The location where the event will be held.', max_length=255, null=True, verbose_name='Location'),
        ),
    ]
