# Generated by Django 5.1.3 on 2024-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(help_text='The name of the event.', verbose_name='Event Name'),
        ),
    ]
