# Generated by Django 5.1.3 on 2024-11-23 13:00

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_name'),
        ('organizers', '0003_organizer_city_district'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city_district',
            field=models.ForeignKey(blank=True, help_text='The district where the event is taking place.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizers.citydistrict', verbose_name='City District'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
