# Generated by Django 5.1.3 on 2024-11-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_city_district_event_tags'),
        ('organizers', '0004_remove_organizer_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='The organizer responsible for this event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizers.organizer', verbose_name='Organizer'),
        ),
    ]
