# Generated by Django 4.2.16 on 2024-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for the event.', null=True, upload_to='event_logos/', verbose_name='Event Logo'),
        ),
    ]
