# Generated by Django 5.1.3 on 2024-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the city district.', max_length=255, verbose_name='District Name')),
            ],
            options={
                'verbose_name': 'City District',
                'verbose_name_plural': 'City Districts',
            },
        ),
    ]
