# Generated by Django 5.1.3 on 2024-11-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_city_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='events',
        ),
    ]
